services:
  frontend:
    image: "ghcr.io/tnfy-link/frontend:latest"
    build:
      context: .
      target: final
    environment:
      - HTTP__ADDRESS=:3000
      - HTTP__PROXY_HEADER=X-Forwarded-For
      - HTTP__PROXIES=127.0.0.1
    ports:
      - 3001:3000
