name: Build and publish docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"

jobs:
  docker:
    permissions:
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Login to Container registry
        if: github.actor != 'dependabot[bot]'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    env:
      DEPLOY_WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL }}
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Trigger Deploy webhook
        if: ${{ env.DEPLOY_WEBHOOK_URL != '' }}
        run: |
          curl -X POST "${DEPLOY_WEBHOOK_URL}" \
          --fail \
          --silent \
          --show-error \
          --max-time 10 \
          --retry 3 \
          --retry-delay 5 \
          || exit 1
